- README.md
> Add: ReadMe 파일 추가

- src/components/Alert.js
- src/components/HiddenMenu.js
- src/pages/profile/MyProfile/index.jsx
- src/pages/profile/YourProfile/index.jsx
- HiddenMenu.js 파일이 추가되었습니다
- Alert.js 파일이 추가되었습니다.
- MyProfile/index.jsx  상태관리 스타일 컴포넌트가 추가되었습니다. 
- YourProfile/index.jsx 상태관리 스타일 컴포넌트가 추가되었습니다. 
- 미해결 과제: HiddenMenu 컴포넌트 내부에 요소를 동적으로 추가 제거 해줘야 하는데 아직 방법을 모르겠습니다. 추후에 해결을 한 후에 모든 페이지에 적용해 나가도록 하겠습니다.
> #1/Bd_ModalCom

- src/components/Form.js
- src/components/UserInfo.js
- src/components/common/image/ProfileImageStyle.js
- src/components/common/image/SymbolImageStyle.js
- src/pages/auth/JoinMemberShip/index.jsx
- src/pages/auth/LoginMain/index.style.js
- src/pages/auth/SetMemberShip/index.jsx
- src/pages/auth/SetMemberShip/index.style.js
- src/pages/post/PostView/index.jsx
- src/pages/post/PostView/index.style.js
- src/pages/profile/MyProfile/index.jsx
- src/pages/profile/YourProfile/index.jsx
Add : ProfileImageStyle 컴포넌트 추가
Add : CommentWrapper 스타일 추가
Add : 컴포넌트, 스타일 적용
> Add : UserInfo 컴포넌트 추가

- package-lock.json
- src/App.js
- src/actions/postActions.js
- src/actions/productActions.js
- src/actions/userActions.js
- src/components/Comment-gh.js
- src/pages/auth/SetMemberShip-gh/index.js
- src/pages/post/PostUpload-gh/index.js
- src/pages/post/PostView-gh/index.js
- src/pages/product/ProductUpdate-gh/index.js
- src/pages/product/ProductUpload-gh/index.js
- src/pages/profile/Myprofile-gh/index.js
- src/pages/profile/MyprofileUpdate-gh/index.js
- src/reducers/userReducers.js
1. -gh 폴더나  gh/ 로 시작되는 라우트는 개별 관리 하도록 하겠습니다.
2. 퍼블리싱 작업과 로직 부분을 독립적으로 운영하여, 충돌을 최소화하고, 보다 더 신속한 개발을 운영하기 위함입니다.
> add: 로직 관련 컴포넌트/라우트 독립적 운영

- src/components/Button.js
- src/pages/auth/JoinMemberShip/index.jsx
- src/pages/auth/JoinMemberShip/index.style.js
- src/pages/auth/LoginEmail/index.jsx
- src/pages/auth/LoginEmail/index.style.js
- src/pages/auth/LoginMain/index.jsx
- Button 컴포넌트 레이아웃 추가했습니다.
- Button + Icon 컴포넌트 레이아웃 추가했습니다.
> #4/Bd_ButtonCom

- src/components/UploadPost.js
- src/pages/post/PostUpload/index.jsx
- src/pages/post/PostUpload/index.style.js
- View페이지 PostUpload 구현했습니다.
- textarea 태그에서 줄넘김 이벤트 발생 시 height값이 자동으로 올라가는 기능에 대해서는 따로 공부를 해야 할 것 같습니다.
- 컴포넌트 폴더에 UploadPost.js 를 생성했습니다.
> #5/Bd_postupdateCom

- README.md
- src/components/Post.js
> Refactor img

- src/components/Button.js
- src/components/Header.js
- src/components/UserInfo.js
- src/pages/auth/JoinMemberShip/index.jsx
- src/pages/auth/LoginEmail/index.jsx
- src/pages/auth/SetMemberShip/index.jsx
- src/pages/home/HomeMain/index.jsx
- src/pages/post/PostUpload/index.jsx
- src/pages/product/ProductUpload/index.jsx
- src/pages/profile/Follower/index.jsx
- src/pages/screen/NotFound/index.jsx
- 각종 버튼 태그들을 추가했습니다.
- 색상은 임시로 orange로 적용했습니다. 이후에 themeProvider를 통해서 색상을 정할 예정입니다.
> Bd button com

- src/App.js
- src/components/Alert.js
- src/components/Header.js
- src/components/HiddenMenu.js
- src/components/Post.js
- src/components/UserInfo.js
- src/pages/chat/ChatList/index.jsx
- src/pages/chat/ChatRoom/index.jsx
- src/pages/home/HomeFeed/index.jsx
- src/pages/post/PostView/index.jsx
- src/pages/post/PostView/index.style.js
- src/pages/profile/MyProfile/index.jsx
- src/pages/profile/YourProfile/index.jsx
- Modal 컴포넌트 추가
- Alert 컴포넌트 추가
> Bd_ModalCom

- src/App.js
- src/components/MainLayOut.js
- src/index.js
- src/styles/theme.js
- theme.js 파일 추가
- App.js에 Provider 태그 추가
- Theme Provider를 추가했습니다.
> Bd_Theme Provider

- src/components/Header.js
- src/components/MainLayOut.js
- src/components/UserInfo.js
- src/pages/home/HomeMain/index.style.js
- src/pages/home/Search/index.jsx
- src/pages/post/PostUpload/index.jsx
- src/pages/post/PostUpload/index.style.js
- src/pages/post/PostView/index.jsx
- src/pages/product/ProductUpload/index.jsx
- src/pages/profile/MyProfile/index.jsx
- src/pages/profile/ProfileModification/index.jsx
- src/pages/screen/NotFound/index.jsx
- src/pages/screen/NotFound/index.style.js
- src/pages/screen/SplashScreen/index.jsx
- src/pages/screen/SplashScreen/index.style.js
- src/styles/theme.js
- 전체적인 레이아웃 컴포넌트 수정
- 현길님께서 기존 작성했던 비즈니스 로직 삭제
> Fix_LayOutCom

- src/components/FollowerList.js
- src/components/Header.js
- src/components/ImgRegister.js
- src/components/MainLayOut.js
- src/pages/product/ProductUpdate/index.jsx
- src/pages/product/ProductUpdate/index.style.js
- src/pages/product/ProductUpload/index.jsx
- src/pages/product/ProductUpload/index.style.js
- src/pages/profile/Follower/index.jsx
- src/styles/GlobalStyles.js
- src/styles/theme.js
- ImgRegister 컴포넌트 추가
- 그 외 레이아웃 문제 해결
> Bd image&lay out com

- src/App.js
- src/components/module/button/button.js
- src/components/module/title/LoginTitle.js
- src/components/template/chat/ChatList.js
- src/components/template/chat/ChatRoom.js
- src/components/template/common/Header.js
- src/components/template/common/Navigation.js
- src/components/template/home/HomeFeed.js
- src/components/template/home/Search.js
- src/components/template/join/JoinEmail.js
- src/components/template/join/JoinProfile.js
- src/components/template/login/LoginEmail.js
- src/components/template/login/LoginMain.js
- src/components/template/post/PostUpload.js
- src/components/template/post/PostView.js
- src/components/template/product/ProductEdit.js
- src/components/template/product/ProductUpload.js
- src/components/template/profile/Follower.js
- src/components/template/profile/Profile.js
- src/components/template/profile/ProfileEdit.js
- src/components/template/screen/NotFound.js
- src/components/template/screen/SplashScreen.js
- src/styles/font.css
- src/styles/theme.js
- 기존 파일과 새로운 파일이 겹치면서 발생하는 라우팅 문제를 해결했습니다
> Fix: 작업환경 재구성 및 라우팅 환경 구성

- src/components/module/upload/UploadPost.js
- src/components/template/post/PostUpload.js
- src/components/template/post/PostView.js
- src/styles/GlobalStyles.js
- PostView 컴포넌트 Build
- PostUpload 컴포넌트 Build
> Bd_postcom

- src/components/module/upload/UploadProfile.js
- src/components/template/product/ProductEdit.js
- src/components/template/product/ProductUpload.js
> Add: Product 컴포넌트

- src/components/module/profile/DisplayButton.js
- src/components/template/profile/Follower.js
- src/components/template/profile/Profile.js
- src/components/template/profile/ProfileEdit.js
- Bd Follower 컴포넌트
- Bd Profile 컴포넌트
- Bd ProfileEdit 컴포넌트
> Bd profile com

- src/components/MainLayOut.js
- src/components/module/Text/SubText.js
- src/components/template/chat/ChatList.js
- src/components/template/profile/ProfileEdit.js
- src/components/template/screen/NotFound.js
- src/components/template/screen/SplashScreen.js
> Bd_Layoutcom

- src/components/template/chat/ChatRoom.js
> Bd: ChatRoom LayOut

- src/components/template/home/HomeFeed.js
> Add: HomeFeed 레이아웃

- src/PAGE/LoginMain.jsx
- src/components/module/button/button.js
- src/components/module/form/LoginForm.js
- src/components/module/form/RegisterForm.js
- src/components/template/join/JoinEmail.js
- src/components/template/join/JoinProfile.js
- src/components/template/login/LoginEmail.js
- src/pages/auth/LoginEmail-gh/index.js
- src/pages/auth/LoginEmail/index.style.js
- 로그인 페이지에서 이메일, 비밀번호 입력시 버튼 활성화 기능을 구현 하였습니다.
- button.js 부분을 일부 수정 하였습니다. (isButtonStatus를 props로 받아서 버튼 활성화 분기 처리)
> add: login form input 입력 시 버튼 활성화 기능 구현

- src/components/Alert.js
- src/components/HiddenMenu.js
- src/components/UserInfo.js
- src/components/module/alert/Alert.js
- src/components/module/form/LoginForm.js
- src/components/module/modal/Modal.js
- src/components/module/user/FollowersUser.js
- src/components/template/chat/ChatList.js
- src/components/template/chat/ChatRoom.js
- src/components/template/home/HomeFeed.js
- src/components/template/join/JoinEmail.js
- src/components/template/join/JoinProfile.js
- src/components/template/login/LoginMain.js
- src/components/template/post/PostView.js
- src/components/template/profile/Profile.js
- src/components/template/screen/NotFound.js
> Bd_alert,modal

- src/components/UserInfo.js
- src/components/module/profile/ProfileIUpload.js
- src/components/template/profile/Profile.js
- product 컴포넌트 Modal & Alert 추가
> Bd_product alert,modal

- src/App.js
- src/PAGE/FollowingList.jsx
- src/PAGE/PostView.jsx
- src/PAGE/ProfileUpdate.jsx
- src/PAGE/Search.jsx
- src/components/module/button/button.js
- src/components/module/form/ProfileForm.js
- src/components/module/post/ReplyBox.js
- src/components/module/user/FollowersUser.js
- src/components/module/user/SearchUser.js
- src/components/template/common/Header.js
- src/components/template/home/Search.js
- src/components/template/post/PostView.js
- src/components/template/profile/Follower.js
- Search 컴포넌트 : Read
- PostView 컴포넌트 : Read,Create
- profileEdit 컴포넌트 : Post
- following 컴포넌트 : Read
> Add: Api_Component

- src/App.js
- src/PAGE/JoinProfile.jsx
- src/PAGE/LoginEmail.jsx
- src/PAGE/PostUpload.jsx
- src/PAGE/ProductUpdate.jsx
- src/PAGE/ProductUpload.jsx
- src/PAGE/Search.jsx
- src/PAGE/YourProfile.jsx
- src/components/module/form/ProductForm.js
- src/components/module/upload/UploadPost.js
- src/components/template/common/Header.js
- src/components/template/common/Navigation.js
- src/components/template/join/JoinEmail.js
- src/components/template/post/PostUpload.js
- src/hooks/useGNB.js
> add: 컴포넌트 데이터 바인딩 작업

- src/PAGE/LoginEmail.jsx
- src/PAGE/ProductUpdate.jsx
- src/components/module/button/button.js
> Bd_formCompo

- src/App.js
- src/PAGE/MyProfile.jsx
- src/PAGE/PostUpload.jsx
- src/actions/postActions.js
- src/actions/userActions.js
- src/components/UserInfo.js
- src/components/module/post/ContentBox.js
- src/components/module/product/Product.js
> add: 데이터 바인딩

- src/App.js
- src/PAGE/FollowerList.jsx
- src/PAGE/FollowingList.jsx
- src/PAGE/Home.jsx
- src/PAGE/JoinProfile.jsx
- src/PAGE/LoginEmail.jsx
- src/PAGE/MyProfile.jsx
- src/PAGE/PostUpload.jsx
- src/components/NoneFeed.js
- src/components/module/alert/Alert.js
- src/components/module/button/button.js
- src/components/module/modal/Modal.js
- src/components/module/product/Product.js
- src/components/template/common/Navigation.js
- 불 필요한 코드 제거
- navigation 버튼 클릭시 색상 적용
- following 팔로우 or 취소 조건부 스타일 적용
- 로그인 및 이메일 버튼 조건부 스타일 적용
- joinemail 컴포넌트 리렌더링시 dispatch 요청 방지
> Refector_component

- src/PAGE/MyProfile.jsx
- src/components/module/button/button.js
- src/components/module/profile/MyUserInfo.js
- src/components/module/profile/YourUserInfo.js
- props 변경
- yourprofile 부분 버튼 해결
> Fix_component

- src/PAGE/Home.jsx
- src/components/module/post/ContentBox.js
- HeaderSlider 스타일링 부분만 수정했습니다.
- Slider 부분은 추후 작업을 다시 이어가도록 하겠습니다.
- const postImages = post?.image?.split(","); 해당 부분에 대한 코드가 충돌이 났습니다. 기존 코드에서 추가하면 되는 부분이니 incomingChange로 해결한 후 다시 머지 하겠습니다.
> Bd_headerSlider

- src/PAGE/MyProfile.jsx
- src/PAGE/YourProfile.jsx
MyProfile, YourProfile 페이지 Gallery Button Handler 기능 추가했습니다.
- PostWrapper태그 불필요하여 제거
- postHeader 부분 galleryHandler 적용
- AlbumGalleryContainer => AlbumGalleryList로 변경
- CardGalleryContainer=> CardGalleryList로 변경
- import ImageLayer 및 import부분 불러온 image만 모아두었습니다.
- PostSectionContainer가 적용되어있지 않아 스타일링을 추가해주었습니다.
> Bd_display_handler

- src/App.js
- src/PAGE/PostView.jsx
- src/PAGE/Search.jsx
- src/styles/GlobalStyles.js
- 미진님과 함께 웹 접근성을 준수하기 위한 태그를 추가했습니다.
- Search, PostView 컴포넌트 내부 label 태그 텍스트 Clip-Path로 해결했습니다.
- [웹 접근성을 고려하여 텍스트 숨기기](https://velog.io/@ursr0706/%EC%9B%B9-%EC%A0%91%EA%B7%BC%EC%84%B1%EC%9D%84-%EA%B3%A0%EB%A0%A4%ED%95%98%EC%97%AC-%ED%85%8D%EC%8A%A4%ED%8A%B8-%EC%88%A8%EA%B8%B0%EA%B8%B0)
> Bd_accessibility

- src/components/module/post/ReplyBox.js
> Fix: 최신댓글 아래에서부터 업로드

- src/App.js
- src/PAGE/MyProfile.jsx
- src/PAGE/MyProfileJY.jsx
- src/components/Profile/ProfileCard/index.jsx
- src/components/Profile/ProfileCard/index.style.js
- src/components/Profile/ProfileContainer/index.jsx
- src/components/Profile/ProfileContainer/index.style.js
- Profile Container 컴포넌트 생성후 데이터 바인딩 및 스타일링 작업
- Profile Card 컴포넌트 생성후 스타일링 및 Props 작업
> Refector: postprfofile

- src/PAGE/MyProfile.jsx
- src/PAGE/MyProfileJY.jsx
- src/components/Profile/ProductCard/index.jsx
- src/components/Profile/ProductCard/index.style.js
- src/components/Profile/ProductContainer/index.jsx
- src/components/Profile/ProductContainer/index.style.js
- src/components/Profile/ProfileContainer/index.jsx
- product container 컴포넌트 생성후 데이터 바인딩 및 스타일링 작업
- product Card 컴포넌트 생성후 스타일링 및 Props 작업
- Alert & Modal 적용
> Refector: product container

- src/components/Profile/ProductContainer/index.jsx
- PostComponent 내부에 모달 태그들 위치 변경했습니다
> Fix: 태그 위치 변경

- src/components/profile/CardGallery/index.jsx
- src/components/profile/CardGallery/index.style.js
- src/components/profile/ProfileCard/index.jsx
- eventTarget을 활용하여 Slider 기능을 구현했습니다.
> Refactoring: slider

- src/App.js
- src/PAGE/LoginMain-JS.jsx
- src/components/Login/index.jsx
- src/components/Login/index.style.js
- src/styles/theme.js
1. 로그인 메인 페이지 분리 완료했습니다.
2. 이미지 불러오는 부분 수정 필요합니다.
3.  버튼 부분 수정 필요합니다.
> Refactoring : Login main

- src/App.js
- src/PAGE/MyProfile.jsx
- src/components/common/CommonHeader/index.jsx
- src/components/common/CommonHeader/index.style.js
- Common 폴더에 Alert, Modal, CommonHeader 추가했습니다.
- CommonHeader 리팩토링 완료를 한 후에 MyProfile에 적용 완료했습니다.
- 확인 후 댓글 부탁드립니다.
- 확인하시면 충돌 해결후 병합하겠습니다.
> Refactoring: header container

- src/PAGE/FollowerList.jsx
- src/PAGE/FollowingList.jsx
- src/PAGE/Home.jsx
- src/components/header/FollowHeader/index.jsx
- src/components/header/FollowHeader/index.style.js
- src/components/header/HomeHeader/index.jsx
- src/components/header/HomeHeader/index.style.js
* components 폴더에 FollowHeader, HomeHeader 추가했습니다
* FollowHeader 리팩토링 완료 후 FollowerList, FollowingList에 적용했습니다.
* HomeHeader 리팩토링 완료 후 Home에 적용했습니다.
> Refactoring: header component

- src/components/Login/index.jsx
- src/components/Login/index.style.js
1. 버튼 링크 연결했습니다.
2. 마무리 디자인 작업이 필요합니다.
> Refactoring : Login main button

- src/PAGE/FollowerList.jsx
- src/PAGE/FollowingList.jsx
- src/PAGE/Home.jsx
- src/PAGE/MyProfile-gh.jsx
- src/PAGE/MyProfile.jsx
- src/PAGE/Search.jsx
- src/PAGE/YourProfile.jsx
- src/components/common/Navbar/index.jsx
- src/components/common/Navbar/index.style.js
- components/common 폴더에 Navbar 추가했습니다.
- Navbar 리팩토링 완료 후 필요한 페이지에 적용했습니다.
> Refactor: Navbar component

- src/components/Login/LoginCard/index.jsx
- src/components/Login/LoginCard/index.style.js
- src/components/Login/LoginContainer/index.jsx
- src/components/Login/LoginContainer/index.style.js
- src/components/Login/SplashCard/index.jsx
- src/components/Login/SplashCard/index.style.js
- SplashScreen 구현완료했습니다.
- 지수님 확인하시고 구현해보시면 좋을 것 같습니다
- 추후 작업으로 이미지 변경 작업을 할 예정입니다.
> Refactoring: splash

- src/components/profile/ProfileCard/index.jsx
- src/components/profile/ProfileCard/index.style.js
- YourProfile 부분 팔로우 버튼 추가했습니다.
- 추후 작업으로는 전달받은 state값에 따라서 yourProfile, MyProfile 부분 보여주면 될 것 같습니다.
> Add: YourProfile 팔로우 버튼 추가

- src/components/PostUpload/index.jsx
- src/components/PostView/PostViewContainer/index.jsx
- src/components/common/image/SymbolImageStyle.js
- src/components/module/post/UserInfoBox.js
- src/components/module/user/FollowersUser.js
- src/components/module/user/SearchUser.js
- src/components/profile/ProfileCard/index.jsx
1. 이미지 경로 수정했습니다.
2. 프로필 이미지 부분 스타일 변경했습니다.
> Refactoring: styling, file

- src/App.js
- src/PAGE/Information.jsx
- src/components/etc/Error/index.jsx
- src/components/etc/Error/index.style.js
- src/components/etc/Loading/index.jsx
- src/components/etc/Loading/index.style.js
- src/components/information/InformationContainer/index.jsx
- src/hooks/usePromise.js
- hook 폴더에 usePromise 생성 했습니다
- 농사랑 API 데이터 패칭 완료했습니다.
- 뉴스에맞는 무료 이미지 dummy data 추가해 두었습니다.
- 농사랑 api에서 이미지 불러와지지 않는 문제 내일 서버에 전화해서 여쭈어보겠습니다
- 그래도 해결이 안된다면 원범님에게 질문해서 해결해보도록 하겠습니다
> Refactoring api

- src/components/Login/LoginEmail/index.jsx
- src/components/module/button/button.js
> Edit : 로그인 타이틀 수정

- src/components/information/InformationContainer/index.jsx
- src/hooks/usePromise.js
- 문제 해결 사항은 노션에 정리했습니다
- https://herman94.notion.site/json-2c01a39d00144187b8196b71f2ecf0f3
- 나중에 여쭈어보신다면 더욱 상세히 말씀드리겠습니다
> Refactoring: 이미지 파일 불러오기 성공

- src/components/PostView/CommentCard/index.jsx
- src/components/PostView/PostViewContainer/index.jsx
> Refactoring: Alert&Modal 미완작업 완료

- src/components/PostView/PostViewContainer/index.jsx
- src/components/PostView/PostViewContainer/index.style.js
- src/components/common/PostCard/index.jsx
- src/components/common/PostCard/index.style.js
- src/components/common/PostIconBox/index.jsx
- src/components/common/PostIconBox/index.style.js
- src/components/profile/GalleryContainer/index.style.js
- src/components/profile/ProductCard/index.style.js
1. 게시글 이미지 클릭 시 슬라이더와 이벤트 겹치는 부분 해결
2. myProfile 부분 게시글 아래짤림 현상 부분 해결
3. 상세페이지 부분 슬라이더 구현
> Refactoring: 상세게시글 슬라이더 구현 및 수정 디테일 추가 및 오전회의사항 반영

- src/components/common/PostCard/index.style.js
- src/components/profile/GalleryContainer/index.jsx
- src/components/profile/GalleryContainer/index.style.js
- src/styles/GlobalStyles.js
1. 이미지 border 제거
2. profile 부분 이미지 부분 배경추가
> Edit: 디테일 수정

- src/components/common/Navbar/index.jsx
- src/components/common/Navbar/index.style.js
> Refactoring: NavLink 적용 완료

- src/PAGE/Join.jsx
- src/components/Join/JoinMember/index.jsx
- src/components/Join/JoinProfile/index.jsx
- src/components/Login/LoginContainer/index.jsx
- src/components/Login/LoginEmail/index.jsx
- src/components/PostView/CommentItem/index.jsx
- src/components/PostView/PostViewContainer/index.jsx
- src/components/common/PostIconBox/index.jsx
- src/components/follow/FollowerContainer/index.jsx
- src/components/follow/FollowingContainer/index.jsx
- src/components/information/InformationContainer/index.jsx
- src/components/profile/ProfileCard/index.style.js
- src/components/search/SearchBar/index.jsx
- src/hooks/usePromise.js
1. 회원가입 프로필 부분 기본이미지 설정되지 않던 부분 수정
2. 회원가입 프로필 부분 입력이미지 불러와지지 않던 부분 수정
3. postView 페이지 post부분 중앙정렬 부분 해결 
1. 파일내에서 참조하고 있지만 사용하고 있지 않은 파일들 삭제했습니다.
마지막까지 화이팅입니다 :)
> Refactoring: delete never use

- src/components/PostView/CommentCard/index.jsx
- src/components/PostView/CommentCard/index.style.js
- src/components/common/Navbar/index.style.js
- src/components/search/SearchBar/index.style.js
- src/components/search/SearchCard/index.jsx
- src/components/search/SearchCard/index.style.js
1. 프로필 이미지 추가했습니다. 하지만 임시적으로 했으며 수정이 필요합니다.
2. serach 페이지에서 이름과, 계정ID 클릭 시에도 해당 유저 프로필로 이동하도록 링크 추가했습니다.
3. 배치가 이상한 부분 스타일 수정했습니다.
> Refactoring : 스타일링 변경, 프로필 이미지 추가

- src/components/PostUpload/index.jsx
- src/components/PostUpload/index.style.js
- src/components/PostView/CommentCard/index.jsx
- src/components/PostView/PostViewContainer/index.jsx
- src/components/common/CommonHeader/index.jsx
- src/components/common/Modal/index.jsx
- src/components/home/HomeContainer/index.jsx
- src/components/profile/GalleryContainer/index.jsx
- src/components/profile/ProductContainer/index.jsx
1. 기존 "닫기" 버튼을 눌러야 사라졌던 modal 버튼 지우고 화면 바깥을 클릭해도 모달창이 꺼지도록 반영
2. [해결 과정 : Click me](https://www.notion.so/herman94/Modal-outside-Click-da8e9d73641347df939bdaabd6dd453c)
> Refactoring: react modal click outside

- src/components/common/Navbar/index.style.js
> Refactoring : navbar right 0 추가

- src/components/search/SearchCard/index.style.js
:last-child(1) 속성을 더해주어 마지막 li태그에 padding bottom을 설정했습니다.
> Refactoring: 유저리스트 간격 조정

- src/components/PostView/CommentCard/index.jsx
- src/components/PostView/PostViewContainer/index.jsx
- src/util/getWhichUser.js
[지수님과 함께 하던 작업](https://herman94.notion.site/accuntname-eacbe86d7350486e9583bd3c80bb9f35)
- 문제 해결했습니다.
> Refactoring: PostView페이지 Profile Img 불러오기

- src/PAGE/FollowerList.jsx
- src/PAGE/FollowingList.jsx
- src/PAGE/Information.jsx
- src/components/PostUpload/index.jsx
- src/components/PostUpload/index.style.js
- src/components/PostView/CommentCard/index.jsx
- src/components/PostView/CommentCard/index.style.js
- src/components/ProductUpload/index.jsx
- src/components/ProductUpload/index.style.js
- src/components/Upload/EditPage/index.jsx
- src/components/Upload/ProductPage/index.jsx
- src/components/common/PostCard/index.jsx
- src/components/information/InformationCard/index.style.js
- src/components/postupdate/index.jsx
- src/components/postupdate/index.style.js
- src/components/productupdate/index.jsx
- src/components/productupdate/index.style.js
- src/components/profile/GalleryContainer/index.jsx
- src/components/profile/ProductContainer/index.style.js
- src/components/profile/ProfileContainer/index.jsx
- src/components/profileupdate/index.jsx
- src/components/search/SearchBar/index.jsx
- src/components/search/SearchBar/index.style.js
- src/styles/GlobalStyles.js
**1. Information 페이지**
- 모바일(iPhone 12 Pro 기준)으로 반응형 작업했습니다.
- `article` `hover` 할 때 스타일을 변경했습니다.
**2. PostUpload, PostUpdate 페이지**
- 마크업, 스타일을 통일했습니다.
- `PhotoList`, `Item`에 미디어쿼리 적용했습니다.
**3. ProductUpload, ProductUpdate  페이지**
- 마크업, 스타일을 통일했습니다.
**4. 웹 접근성을 위한 클래스명 통일**
- `a11y-hidden` 로 목적에 맞는 클래스명을 사용했습니다.
> Refactoring: Information 반응형, Update 페이지 통일성

- src/pages/Join.jsx
- src/pages/LoginEmail.jsx
- src/pages/LoginMain.jsx
- src/pages/PostView.jsx
> Refactoring: 경로 설정 문제 해결

- src/components/common/Modal/index.style.js
- src/components/common/Navbar/index.style.js
- src/components/common/PostIconBox/index.jsx
- src/components/follow/FollowingContainer/index.jsx
- src/components/home/HomeContainer/index.jsx
- src/components/join/JoinMember/index.jsx
- src/components/login/LoginEmail/index.jsx
- src/components/postUpdate/index.jsx
- src/components/postUpload/index.jsx
- src/components/postView/CommentCard/index.jsx
- src/components/postView/PostViewContainer/index.jsx
- src/components/postView/PostViewContainer/index.style.js
- src/components/productUpdate/index.jsx
- src/components/profile/GalleryContainer/index.jsx
- src/components/profile/ProductContainer/index.jsx
- src/components/profile/ProfileContainer/index.jsx
- src/components/profileUpdate/index.style.js
- src/components/search/SearchBar/index.jsx
- src/styles/GlobalStyles.js
- src/styles/theme.js
- [ [Refactroing] 리팩토링 1회차 #불필요 코드 제거 #메모리 누수 제거하기 ](https://herman94.notion.site/Refactroing-1-9bd858801d7342c693d00d4a0cc97f06)
> Refactoring: clean code

- src/components/postView/CommentCard/index.jsx
- src/components/postView/CommentItem/index.jsx
- src/components/postView/CommentItem/index.style.js
- src/components/postView/PostViewContainer/index.style.js
1. 프로필 이동 link 추가했습니다.
2. 모달 이벤트 버튼에서만 동작하도록 변경했습니다.
3. 불필요한 주석 제거했습니다.
> Refactoring : postview 페이지 link 추가
